- name: Setup and configure AWS components for scoreboard
  hosts: all
  become: true
  gather_facts: false 
  tasks:

  - name: Fail if not on a CTF challenges instance
    assert: { that: "ec2_tag_Name == '{{ challenges_name }}'" }

  - name: Update yum repository and upgrade packages
    yum: name=* state=latest

  - name: Install packages for monitoring containers
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - python27-pip

  - name: Update pip
    command: pip install --upgrade pip creates=/usr/local/bin/pip

  - name: Install docker-py pip package
    pip:
      name: docker-py
      state: present
      executable: /usr/local/bin/pip

  - name: Add instance to the challenges server
    template:
      src: templates/ecs.config.j2
      dest: /etc/ecs/ecs.config
    notify: Restart ecs step 1

  handlers:

    - name: Restart ecs step 1 
      command: stop ecs
      notify: Restart ecs step 2

    - name: Restart ecs step 2
      file:
        path: /var/lib/ecs/data/ecs_agent_data.json
        state: absent
      notify: Restart ecs step 3

    - name: Restart ecs step 3
      command: start ecs

