---
- name: Setup AWS components for scoreboard infrastructure
  hosts: localhost
  connection: local
  tasks:

  - name: Provision VPC for CTF
    ec2_vpc:
      state: present
      cidr_block: "{{ scoreboard_vpc_cidr_block }}"
      resource_tags: { "Name":"{{ scoreboard_vpc_name }}" }
      region: "{{ aws_region }}"
      internet_gateway: true
      wait: yes
    register: subnet 

  - name: Debug - vpc_id
    debug: var=subnet['vpc_id'] verbosity=2

  - name: Create subnet for scoreboard
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ subnet['vpc_id'] }}"
      region: "{{ aws_region }}"
      cidr: "{{ scoreboard_cidr }}"
      resource_tags:
        Name: "{{ scoreboard_subnet_name }}"
    register: scoreboard_subnet

  - name: Debug - subnet_id 
    debug: var=scoreboard_subnet['subnet']['id'] verbosity=2

  - name: Configure public route table for VPC
    ec2_vpc_route_table:
      vpc_id: "{{ subnet['vpc_id'] }}"
      region: "{{ aws_region }}"
      tags:
        Name: "{{ scoreboard_route_table_name }}" 
      subnets:
        - "{{ scoreboard_subnet['subnet']['id'] }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ subnet['igw_id'] }}"

  - name: Configure security group for server
    ec2_group:
      name: "{{ scoreboard_security_group }}"
      description: Security rules for CTF scoreboard
      vpc_id: "{{ subnet['vpc_id'] }}"
      region: "{{ aws_region }}"
      rules:
        - proto: tcp
          from_port: 22 
          to_port:  22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443 
          to_port:   443
          cidr_ip: 0.0.0.0/0

  - name: Create key pair from local file
    ec2_key:
      name: "{{ scoreboard_key_name }}"
      key_material: "{{ item }}"
      region: "{{ aws_region }}"
    with_file: "{{ scoreboard_key_path }}"

  - name: Provision EC2 container instance for scoreboard
    ec2:
      instance_type: "{{ scoreboard_instance_type }}"
      image: "{{ scoreboard_ami_id }}"
      key_name: "{{ scoreboard_key_name }}"
      wait: true
      exact_count: 1
      count_tag:
        Name: "{{ scoreboard_name }}"
      instance_tags:
        Name: "{{ scoreboard_name }}"
      vpc_subnet_id: "{{ scoreboard_subnet['subnet']['id'] }}"
      region: "{{ aws_region }}"
      group: "{{ scoreboard_security_group }}"
    register: scoreboard
  
  - name: Debug - scoreboard instance_id
    debug: var=scoreboard['tagged_instances'][0]['id'] verbosity=2
  
  - name: Add Elastic IP to VPC for use with EC2 instance
    ec2_eip:
      device_id: "{{ scoreboard['tagged_instances'][0]['id'] }}"
      state: present
      in_vpc: yes
      region: "{{ aws_region }}"
  
  - name: Debug - Print all variables
    debug: var=hostvars[inventory_hostname] verbosity=4

